name: Build

on:
  push:
    branches:
      - bugfix/build

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild TrayPlum.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
    - name: Find artifacts
      run: Get-ChildItem -Path . -Recurse -filter *.exe
    - name: Where am I?
      run: Get-ChildItem -Path .
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: helik-dist
        path: |
          Release\TrayPlum.exe

